### PR TITLE
Add mining related requests

### PR DESCRIPTION
**Pull request by Lignumm**
- [x] Get work
- [x] Submit block
- [x] Get last block

### CODE REVIEW

**Comment by demhydraz** [comment]
Ok, this looks good

**Comment by Lignumm** [comment]
It is mergable, I'll un-POST it in a separate PR at some point.

**Comment by demhydraz** [comment]
:ack:

**Comment by demhydraz** [comment]
I don't need tests. I have _types_!

**Comment by Lignumm** [comment]
λλλλ

**Pull request merged**
