### PR TITLE
Private key generation

### PR DESCRIPTION
**Pull request by Lignumm**
Pretty straight forward, adds `Data.Krist.PrivateKey.makeKWPrivateKey`, which returns a private key for any KristWallet password.

### CODE REVIEW

**Comment by demhydraz** [comment]
this is :good: :+1:

**Comment by Lignumm** [comment]
:cool: man thanks :white_check_mark:

**Comment by demhydraz** [comment]
is that like a poor man's ack

**Comment by Lignumm** [comment]
yes

**Pull request merged**
